name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  TERM: linux
  FORCE_COLOR: 1

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Restore
        run: npm ci

      - name: Build
        run: |
          npm run build
          npx wurk publish --no-build --to-archive
          npx wurk test --no-build

      - name: Publish (Dry Run)
        run: npx wurk publish --from-archive --dry-run
