name: Push

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [current]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Restore
        run: npm ci

      - name: Build
        run: |
          npm -ws --if-present run build
          npm update @werk/cli
          npx @werk/cli publish --to-archive

      - name: Test
        run: npm test

      # - name: Publish (CodeCov)
      #   if: github.ref == 'refs/heads/main'
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./out/coverage/lcov.info
      #     fail_ci_if_error: true
      #     verbose: true

      - name: Publish (NPM)
        run: |
          npm config set //registry.npmjs.org/:_authToken '${NPM_TOKEN}'
          npx @werk/cli publish --from-archive
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
