name: Push

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

env:
  TERM: xterm-256color
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore
        run: |
          set -e
          corepack enable
          pnpm install --frozen-lockfile

      - name: Build
        run: |
          set -e
          pnpm build
          pnpm dlx wurk publish --to-archive
          pnpm test

      - name: Publish
        run: |
          set -e
          npm config set //registry.npmjs.org/:_authToken '${NPM_TOKEN}'
          pnpm dlx wurk publish --from-archive
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
